---
title: "Weight of Fish"
author: "Kristina Larson"
date: "November 2020"
output: 
  html_document:
    number_sections: true
    toc: true
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

## Build the best regression model you can that predicts the weight of perch
## Using only two predictor variables  


# Perch Model  


```{r}
#read in the fish data
fishdata <- read.csv(file="Fish.csv",header=TRUE)
PerchData <-filter(fishdata,Species=="Perch") %>% select(-Species)

```
#now automate


```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = PerchData,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```

```{r}
PerchModel<- lm(Weight~Height+Width, data=PerchData)
summary.lm(PerchModel)
```

The best 2 regression model for the perch fish is the Height Width with an adjusted R-squared of .94. 

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->




# Bream Model 
```{r}
#read in the fish data
fishdata <- read.csv(file="Fish.csv",header=TRUE)
BreamData <-filter(fishdata,Species=="Bream") %>% select(-Species)

```


# Smelt Model 
```{r}
#read in the fish data
fishdata <- read.csv(file="Fish.csv",header=TRUE)
SmeltData <-filter(fishdata,Species=="Smelt") %>% select(-Species)

```



# Discussion and Final Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
